name: Docker Image CI

on:
  push:
    branches: 
      - master
      - 7.4
    tags: 
      - 7.4
  pull_request:
    branches: 
      - master
      - 7.4
    tags: 
      - 7.4

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to docker hub
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASS: ${{secrets.DOCKER_PASS}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASS
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{secrets.DOCKER_USER}}/${{secrets.DOCKER_IMAGE}}:$(date +%s)
    - name: Push to docker hub
      run: docker push ${{secrets.DOCKER_USER}}/${{secrets.DOCKER_IMAGE}}
